Exposing ports to the host causes the tests to be flaky.
ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint db (7a7976dfaf7ead9b104702282b06bab15691f264bff93806abd17ddf10490a3a): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use

I think this happens because other tests are using the same port
ocassionally. Moving to using a separate test docker-compose file
so we don't have to mest with the development travis file.