fix: s/price_excl_tax/price for django oscar 3.1 upgrade
The Django Oscar 3.1 upgrade renames table
partner_stockrecord.price_excl_tax to partner_stockrecord.price:

https://github.com/openedx/ecommerce/blob/8cd7c39689954a16694d89eefe850fc6bca2462a/ecommerce/extensions/partner/migrations/0019_auto_20231108_1355.py#L44-L48

This commit mirrors the rename in course-discovery.

Without this rename, I get on devstack:

    2024-03-15 18:56:57,271 ERROR 200 [course_discovery.apps.course_metadata.management.commands.refresh_course_metadata] /edx/app/discovery/discovery/course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py:40 - EcommerceApiDataLoader failed!
    Traceback (most recent call last):
      File "/edx/app/discovery/discovery/course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py", line 37, in execute_loader
        run_loader()
      File "/edx/app/discovery/venvs/discovery/lib/python3.8/site-packages/backoff/_sync.py", line 105, in retry
        ret = target(*args, **kwargs)
      File "/edx/app/discovery/discovery/course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py", line 34, in run_loader
        return loader_class(*loader_args).ingest()
      File "/edx/app/discovery/discovery/course_discovery/apps/course_metadata/data_loaders/api.py", line 348, in ingest
        self._load_ecommerce_data()
      File "/edx/app/discovery/discovery/course_discovery/apps/course_metadata/data_loaders/api.py", line 370, in _load_ecommerce_data
        self._process_course_runs(course_runs)
      File "/edx/app/discovery/discovery/course_discovery/apps/course_metadata/data_loaders/api.py", line 488, in _process_course_runs
        self.update_seats(body)
      File "/edx/app/discovery/discovery/course_discovery/apps/course_metadata/data_loaders/api.py", line 553, in update_seats
        self.update_seat(course_run, product_body)
      File "/edx/app/discovery/discovery/course_discovery/apps/course_metadata/data_loaders/api.py", line 575, in update_seat
        price = Decimal(stock_record['price_excl_tax'])
    KeyError: 'price_excl_tax'
    CommandError: One or more of the data loaders above failed.